sample/ComputeShader : 'Added writeonly qualifier to fix CS compilation error. '0(3) : error C7596: OpenGL requires image variables declared without using the 'writeonly' qualifier to have a format layout qualifier'